In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/opt/conda/envs/ml-zoomcamp/lib/python3.11/site-packages/numpy/__init__.py'>

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
a = np.array([1, 2, 3, 5, 7, 12])

In [7]:
a[2] = 10

In [8]:
a

array([ 1,  2, 10,  5,  7, 12])

In [10]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [15]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

Multi-dimensional arrays

In [2]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [3]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [4]:
n[0, 1] = 20

In [15]:
n

array([[1, 1, 1],
       [4, 5, 6],
       [1, 1, 1]])

In [10]:
n[2] = [1, 1, 1]

In [16]:
n

array([[1, 1, 1],
       [4, 5, 6],
       [1, 1, 1]])

In [19]:
n[:, 2] = [0, 1 , 2]

In [20]:
n

array([[1, 1, 0],
       [4, 5, 1],
       [1, 1, 2]])

In [13]:
np.array([[2, 4, 6,],
          [8, 10, 12],
          [14, 16, 18]])

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

Randomly generated arrays

In [25]:
np.random.seed(2)
100 * np.random.rand(5,2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [24]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [26]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

Element-wise operations